baseURL: "/"
languageCode: en-us
title: Conholdate
theme: "PaperMod"
paginate: 10
enableRobotsTXT: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  mainSections: # Add name of each folder under content folder that contains blog posts.
  - Conholdate.Total # https://gohugo.io/functions/where/#mainsections
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: true

############ Localization #########################
languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Francais
    weight: 2
    menu:
      main:
      - identifier: search
        name: Chercher
        url: /chercher/
        weight: 10
      - identifier: categories
        name: Catégories
        url: /categories/
        weight: 20
      - identifier: archive
        name: Archiver
        url: /les-archives/
        weight: 30
      - identifier: tags
        name: "Mots clés"
        url: /tags/
        weight: 40
  zh:
    languageName: Chinese
    weight: 3
    menu:
      main:
      - identifier: search
        name: 搜索
        url: /搜索/
        weight: 10
      - identifier: categories
        name: 类别
        url: /类别/
        weight: 20
      - identifier: archive
        name: 档案
        url: /档案/
        weight: 30
      - identifier: tags
        name: 标签
        url: /标签/
        weight: 40
###################################################

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40